# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True, verbose_name=b'Date of Final')),
                ('relay', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_display', models.CharField(max_length=50, verbose_name=b'Season Best')),
                ('time_full', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=1)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Event')),
            ],
            options={
                'ordering': ['time_full'],
            },
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Team Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Swimmer'),
        ),
        migrations.AddField(
            model_name='choice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Event'),
        ),
        migrations.AddField(
            model_name='choice',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Participant'),
        ),
        migrations.AddField(
            model_name='choice',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('event', 'swimmer')]),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('team', 'event')]),
        ),
    ]
