# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='time_display',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='time_full',
        ),
        migrations.AddField(
            model_name='participant',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Season Best'),
        ),
    ]
