# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0002_auto_20160614_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='wr_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rio.Event'),
        ),
    ]
