# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0003_auto_20160615_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='wr_choice',
            new_name='WR_event',
        ),
    ]
