# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='Season Best')),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Swimmer'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Participant'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rio.Team'),
        ),
    ]
