# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0004_auto_20160607_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nomination',
            new_name='Choice',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Final'),
        ),
    ]
