# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0005_auto_20160607_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='name',
        ),
    ]
