# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0006_auto_20160607_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'Team Name'),
        ),
    ]
