# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0008_auto_20160616_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[(b'Y', b'Confirmed'), (b'N', b'Unconfirmed'), (b'X', b'Not swimming')], default=b'N', max_length=1),
        ),
    ]
