# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0008_auto_20160612_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
