# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0009_auto_20160621_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[(b'Confirmed', b'Confirmed'), (b'Unconfirmed', b'Unconfirmed'), (b'Not swimming', b'Not swimming')], default=b'Unconfirmed', max_length=12),
        ),
    ]
