# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0009_auto_20160612_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AddField(
            model_name='event',
            name='relay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
