# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0010_auto_20160614_0836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('team', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('event', 'swimmer')]),
        ),
    ]
