# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0011_auto_20160614_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['time_full']},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='time',
            new_name='time_display',
        ),
        migrations.AddField(
            model_name='participant',
            name='time_full',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Season Best'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([]),
        ),
    ]
