# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0012_auto_20160709_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name=b'Date Created'),
        ),
    ]
