# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0014_auto_20160709_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Created'),
        ),
    ]
