# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0016_auto_20160709_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'League Description'),
        ),
    ]
