# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0020_auto_20160719_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rio.Event'),
        ),
    ]
