# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 21:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0021_news_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(b'^[^\\]*$')], verbose_name=b'Team Name'),
        ),
    ]
