# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0023_auto_20160803_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scored',
            field=models.BooleanField(default=False),
        ),
    ]
