# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rio', '0024_event_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[(b'result', b'result'), (b'wr', b'wr'), (b'summary', b'summary'), (b'other', b'other')], default=b'other', max_length=12),
        ),
    ]
